### ISSUE TITLE
Can I pass in multiple parameters?

### ISSUE THREAD

**Issue by gsteinbacher** [pomma89/Thrower#2]
First of all, very nicely done!

I want to be able to pass in multiple parameters.  Here is my use case...

`
if (!File.Exists(pdfPath))
  throw new FileNotFoundException("PDF file not found" pdfPath);
`

I want to change this to ...

`
            Raise<FileNotFoundException>.If(!File.Exists(pdfPath), "PDF file not found", pdfPath);
`

I can't find a way to pass in the `pdfpath` as the third parameter so it will be included as the second parameter of the `FileNotFoundException`.  Is this possible?

**Comment by pomma89** [comment]
Hi Gene,

As you noticed, right now it is not possible to write that code. However, if you can wait till Sunday, I will implement a custom `ExceptionHandler` for `FileNotFoundException`, so that you will be able to write code like this:

    Raise.FileNotFoundException.If(condition, path, msg);
    Raise.FileNotFoundException.IfNot(condition, path, msg);
    Raise.FileNotFoundException.IfFileNotExists(path, msg);

If this is OK for you, then on Sunday I will implement and publish the new handler. If you have other exceptions for which you think an handler should exist, please suggest them in a separate issue.

**Comment by pomma89** [comment]
Done and [released on NuGet](https://www.nuget.org/packages/Thrower/3.0.2).

Closing the issue, let me know if this does not solve your problem.

**Comment by gsteinbacher** [comment]
Works great.  Thanks!
